### ISSUE TITLE
Add support of Kotlin/Native

### ISSUE THREAD

**Issue by caffeine-mgn** [hiperbou/kotlin-unreal#16]
Can you add support of kotlin native?

**Comment by hiperbou** [comment]
Kotlin/Native is out of scope of this project. This project is meant to INCREASE productivity in Unreal 4/5 by offering another language to code gameplay and using Kotlin/Native would result in the opposite, because you will get all the downsides Unreal has by using C++ plus the unconvenient compilation times of Kotlin/Native.
Also, Kotlin/Native, as far as I know, doesn't have support for consoles wich will reduce your targets to only Windows/Mac/Linux.

On the other side, the good news is, Kotlin/Native is made to be interoperable with C code, so there's nothing stopping you from using it with Unreal as you would in any other K/N project using C libraries. You could write your Kotlin code and use it as a library from your Unreal project as long as you don't mind the downsides I mentioned.
I would advise against doing this, but it really depends on your use case.

Anyway, what would be the use case that requires the use of K/N in your project?

**Comment by caffeine-mgn** [comment]
okey, you right. How slowly kotlin js work if compare with native C++?

**Comment by hiperbou** [comment]
Everything is slower than C++, and KotlinJs (or even Kotlin/Native) is expected to perform slower.

I made a simple benchmark that you can find in the wiki, that compares actors being ticked every frame with Kotlin and Blueprints.
The results for this are comparable to Blueprints although still a little slower in this test:
https://github.com/hiperbou/kotlin-unreal/wiki/Benchmark

I'm not sure if a real world game would need update so many actors at once, maybe a real time strategy game, so it really depends on the kind of game you're aiming at. Also, the benchmark shows that you will get into problems using Blueprints too in this case.

In the end using Kotlin with Unreal is not an exclusive decision, as you can continue using both Blueprints and C++ code along with Kotlin. 
I really think that KotlinJS is perfectly suitable for many genres and if you end up finding a bottleneck, you could always port the slow code to C++, wich would be easier than porting from a Blueprint.
