### ISSUE TITLE
How do you successfully compile the `_part_#_ue.kt` files?

### ISSUE THREAD

**Issue by IvanEOD** [hiperbou/kotlin-unreal#28]
Every time I try to compile them myself I get heap space error, then when I turn the heap space up to compile them.. it will just compile for hours and never finish. Was wanting to make some modifications, but I can't even get them to compile as-is

**Comment by IvanEOD** [comment]
Thanks, I will try this!

Would adding <code>@JsName</code> annotations make a big difference, do you think?

**Comment by hiperbou** [comment]
What are you trying to do? @JsName annotations are used to change the name of a kotlin identifier once it is compiled to javascript.

So having:

```
@JsName("myJsNameFunction")
fun myKotlinFunction() = "Hello"
```

if will compile to a Javascript function named "myJsNameFunction" instead of "myKotlinFunction"


If there is some Unreal class that the current definitions returns something that is not correct or that you know that it is from another type, you can erase the type by using .asDynamic()
Here are some uses on this repository to work around some too restrictive type conversions:

https://github.com/search?q=repo%3Ahiperbou%2Fkotlin-unreal%20asdynamic&type=code

**Comment by IvanEOD** [comment]
I'm trying to compile with kotlin naming conventions, but still connect to the existing declarations...

![image](https://user-images.githubusercontent.com/77090686/233670055-128a8520-0371-435c-9318-72d3870c8945.png)

If you have it:
Discord: `IvanEOD#8755`
